export const concertsData = [
  {
    id: 1,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 1",
    date: "2023-07-15",
    description: "Concert by Band 1",
    location: "Music Hall",
  },
  {
    id: 2,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 2",
    date: "2023-08-20",
    description: "Concert by Band 2",
    location: "Arena Stadium",
  },
  {
    id: 3,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 3",
    date: "2023-09-10",
    description: "Concert by Band 3",
    location: "Outdoor Park",
  },
  {
    id: 4,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 4",
    date: "2023-09-25",
    description: "Concert by Band 4",
    location: "Theater Hall",
  },
  {
    id: 5,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 5",
    date: "2023-10-05",
    description: "Concert by Band 5",
    location: "Club Venue",
  },
  {
    id: 6,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 6",
    date: "2023-10-20",
    description: "Concert by Band 6",
    location: "Convention Center",
  },
  {
    id: 7,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 7",
    date: "2023-11-12",
    description: "Concert by Band 7",
    location: "Stadium Arena",
  },
  {
    id: 8,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 8",
    date: "2023-11-25",
    description: "Concert by Band 8",
    location: "Open Air Park",
  },
  {
    id: 9,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 9",
    date: "2023-12-10",
    description: "Concert by Band 9",
    location: "Music Hall",
  },
  {
    id: 10,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 10",
    date: "2023-12-18",
    description: "Concert by Band 10",
    location: "Theater Hall",
  },
  {
    id: 11,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 11",
    date: "2024-01-05",
    description: "Concert by Band 11",
    location: "Club Venue",
  },
  {
    id: 12,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 12",
    date: "2024-01-15",
    description: "Concert by Band 12",
    location: "Outdoor Park",
  },
  {
    id: 13,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 13",
    date: "2024-02-10",
    description: "Concert by Band 13",
    location: "Arena Stadium",
  },
  {
    id: 14,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 14",
    date: "2024-02-18",
    description: "Concert by Band 14",
    location: "Theater Hall",
  },
  {
    id: 15,
    img: "https://www.adorama.com/alc/wp-content/uploads/2018/11/landscape-photography-tips-yosemite-valley-feature.jpg",
    artist: "Band 15",
    date: "2024-03-05",
    description: "Concert by Band 15",
    location: "Open Air Park",
  },
];
